name: t3

#eclipse:
#    min: 4.6
#   
#workspace:
#    workingSet:
#        name: t3
#
#    launchers:
#        launcher:
#            name: package_t3
#            command: mvn clean package