image: debovema/docker-mvn

before_script:
    - chmod u+x release.sh
    - . ./release.sh

release:
    script:
        - mvn -gs /home/m2/settings.xml -Dunleash.developmentVersion=$DEV_VERSION -Dunleash.releaseVersion=$RELEASE_VERSION -Dunleash.scmUsername=debovema -Dunleash.scmPasswordEnvVar=GIT_PASSWORD -Dunleash.profiles=release-profile,t3-archive -P release-profile,t3-archive unleash:perform
        - "curl -X POST -F token=$REBUILD_TOKEN -F ref=master https://git.teecu.be/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline"
        - "curl -X POST -F token=$REBUILD_TOKEN -F ref=v$RELEASE_VERSION https://git.teecu.be/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline"
    only:
        - release
